export const FETCH_BEGIN   = 'FETCH_BEGIN';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const ADD_REVIEW = 'ADD_REVIEW';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const FETCH_DETAIL_BEGIN = 'FETCH_DETAIL_BEGIN';